sudo: required

#language: generic

services:
  - docker

#script:
#  - docker --version  # document the version travis is using
#  - docker-compose -f src/Docker/docker-compose.yml -f src/Docker/docker-compose.release.yml -p ironclad config
#  - docker-compose -f src/Docker/docker-compose.yml -f src/Docker/docker-compose.release.yml -p ironclad build
#  - docker login lykkecloud.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
#  - docker tag ironclad:latest lykkecloud.azurecr.io/ironclad:latest
#  - docker push lykkecloud.azurecr.io/ironclad:latest
  
  
language: csharp
mono: none
dotnet: 2.1.403
services:
 - postgres
env:
 - POSTGRES_CONNECTIONSTRING="Host=localhost;Database=ironclad;Username=postgres;Password=;" GOOGLE_CLIENT_ID="foo" GOOGLE_SECRET="bar"
script:
 - dotnet build ./src/Ironclad.sln
 - dotnet test ./src/tests/Ironclad.Tests/Ironclad.Tests.csproj
