sudo: required

language: generic

services:
  - docker

script:
  - docker --version  # document the version travis is using
  - docker-compose -f src/Docker/docker-compose.yml -f src/Docker/docker-compose.release.yml -p ironclad build
  - docker login lykkecloud.azurecr.io -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
  - docker tag ironclad_nginx:latest lykkecloud.azurecr.io/ironclad_nginx:latest
  - docker push lykkecloud.azurecr.io/ironclad_nginx:latest
  - docker tag ironclad:$VERSION lykkecloud.azurecr.io/ironclad:$VERSION
  - docker push lykkecloud.azurecr.io/ironclad:$VERSION