version: '3'

services:
  ironclad:
    image: ironclad
    container_name: ironclad
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ../Ironclad/
      dockerfile: Dockerfile
  nginx:
    image: nginx
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile