version: '3'

services:
  ironclad:
    image: ironclad:$version
    container_name: ironclad
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ../Ironclad/
      dockerfile: VisualStudio.Dockerfile
  nginx:
    image: ironclad_nginx:$version
    container_name: nginx
    build:
      context: nginx/
      dockerfile: Dockerfile