version: '3'

services:

  nginx:
    image: nginx:1.13.8-alpine
    depends_on:
      - ironclad
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH:-/var/log}:/var/log
    ports:
      - "5005:80"
#    network_mode: bridge

  ironclad:
    ports:
      - "5006:80"