version: '3'

services:
  ironclad:
    image: ironclad:${VERSION:-0.0.1-developer}
    container_name: ironclad
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    build:
      context: ../Ironclad/
      dockerfile: VisualStudio.Dockerfile
      args:
        version: ${VERSION:-0.0.1-developer}

  nginx:
    image: ironclad_nginx
    container_name: ironclad_nginx
    build:
      context: nginx/
      dockerfile: Dockerfile
  
  postgres:
    image: postgres:9.6-alpine
    environment:
      - POSTGRES_DB=IronClad
      - POSTGRES_USER=ironClad
      - POSTGRES_PASSWORD=secureKey
      - POSTGRES_ROOT_PASSWORD=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: