version: '3.4'

services:

  nginx:
    image: nginx:1.13.8-alpine
    depends_on:
      - ironclad
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ${LOG_PATH:-/var/log}:/var/log
    ports:
      - "5005:80"

  ironclad:
    environment:
      IRONCLAD_CONNECTIONSTRING: ${IRONCLAD_CONNECTIONSTRING}
      INTROSPECTION_SECRET: ${INTROSPECTION_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      GOOGLE_SECRET: ${GOOGLE_SECRET}
    ports:
      - "5006:80"