version: '3.4'

services:

  ironclad:
    image: ironclad:${TAG:-dev}
    container_name: ironclad
    environment:
      ASPNETCORE_ENVIRONMENT: Docker
    env_file:
      - ./default.env
    build:
      context: ../Ironclad/
      dockerfile: VisualStudio.Dockerfile
      args:
        version: ${VERSION:-0.1.0-developer}
    volumes:
      - ${LOG_PATH:-/logs}:/app/logs
