version: '3'

services:

  ironclad:
    image: ironclad:${TAG:-dev}
    container_name: ironclad
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker
    env_file:
      - ./.env
      - ./default.env
    build:
      context: ../Ironclad/
      dockerfile: VisualStudio.Dockerfile
      args:
        version: ${VERSION:-0.1.0-developer}
    volumes:
      - ${LOG_PATH:-/logs}:/app/logs
